DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE FOLLOWS CASCADE CONSTRAINTS;
DROP TABLE TWEETS CASCADE CONSTRAINTS;
DROP TABLE MULTIMEDIA CASCADE CONSTRAINTS;



CREATE TABLE USERS
(
  USERID VARCHAR(20) NOT NULL PRIMARY KEY,
  UNAME VARCHAR(30)
);

CREATE TABLE FOLLOWS
(
  FOLLOWER VARCHAR(20) NOT NULL,
  USERID VARCHAR(20) NOT NULL,
  PRIMARY KEY (FOLLOWER, USERID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE TWEETS
(
  USERID VARCHAR(20) NOT NULL,
  TID VARCHAR(20) NOT NULL,
  PRIMARY KEY (USERID, TID),
  MSG CLOB NOT NULL, --VARCHAR(MAX)
  TSTAMP TIMESTAMP,
  FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE MULTIMEDIA
(
  TID VARCHAR(20) NOT NULL PRIMARY KEY,
  MEDIA BLOB,
  FOREIGN KEY(TID) REFERENCES TWEETS(TID) ON DELETE CASCADE
);

INSERT INTO USERS
VALUES ('420', 'ERNEST');

INSERT INTO USERS
VALUES ('60', 'BLERNEST');

INSERT INTO USERS
VALUES ('7', 'KERNEST');

INSERT INTO USERS
VALUES ('80', 'BEEP');

INSERT INTO USERS
VALUES ('1', 'MO');
