DROP TABLE USERS;
DROP TABLE FOLLOWS;
DROP TABLE TWEETS;
DROP TABLE MULTIMEDIA;



CREATE TABLE USERS
(
  USERID VARCHAR(20) NOT NULL PRIMARY KEY,
  UNAME VARCHAR(30)
);

CREATE TABLE FOLLOWS
(
  FOLLOWER VARCHAR(20) NOT NULL,
  USERID VARCHAR(20) NOT NULL,
  PRIMARY KEY (FOLLOWER, USERID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE TWEETS
(
  USERID VARCHAR(20) NOT NULL,
  TID VARCHAR(20) NOT NULL,
  PRIMARY KEY (USERID, TID),
  MSG CLOB, --VARCHAR(MAX)
  TSTAMP TIMESTAMP
);

CREATE TABLE MULTIMEDIA
(
  TID VARCHAR(20) NOT NULL PRIMARY KEY,
  MEDIA BLOB
);

INSERT INTO USERS
VALUES ('420', 'ERNEST');

INSERT INTO USERS
VALUES ('60', 'BLERNEST');

INSERT INTO USERS
VALUES ('7', 'KERNEST');

INSERT INTO USERS
VALUES ('80', 'BEEP');

INSERT INTO USERS
VALUES ('1', 'MO');
